# Methods

## About the Analyses

Canadian Migration Monitoring Network trends are displayed only for species at each site that meet the following criteria:

-   Standardized count protocols are followed consistently through time, for a minimum of 10 years.
-   The species is regularly observed within and between seasons (averaging 10+ detections/season and detection on 5+ days/season).
-   Analysis codes are assigned to all species, based on station and season specific migration patterns (updated 2023), to help with the interpretation of trend outputs (see Species Classification). Specifically, trends for species meeting criteria 'M' (regular migrants) can be interpreted as representing change in population size within a large area of the stations' catchment area (the portion of breeding range sampled by that station). Trends for species in other classification groups may also represent broad-scale population change, but require case-by-case evaluation.
-   For 'M' species, models were fit to standardized counts (banding and/or census), whereas all other species were fit to daily estimated totals (DETs). In instances where 'M' species did not meet minimum observation requirements (detailed above), they were subsequently assessed using DETs as the response variable (assuming DET met the minimum observation requirements).

## Count Variables

Note: In the BMDE different column represent different count types.

-   ObservationCount = Daily Estimated Totals
-   ObservationCount2 = DST
-   ObservationCount3 = Census
-   ObservationCount4 = Banded
-   ObservationCount5 = Other (recap, stopover, repeat)
-   ObservationCount6 = Other (visual migration, observations outside of census)

You can change the observation count used for the analysis by changing the 'obs.var' value in the "CMMN_Analysis_ParameterValues.csv" file saved in the `Data` folder.

## Species classification

All species at each site are classified using the following describes:

**M** Regular migrant, 75+% of season covered by station in 2/3 or more of all years, few individuals present before or after clear migratory surge. Species is well-monitored at the site. Trends are of good quality, and represent change in population size for a large area of the station's catchment area.

**ML** Similar to M, except that numbers before/after migratory peak (i.e. local area birds) amount to more than a quarter of peak numbers during the migratory surge. Although the analysis window is limited to the period of migratory surge, the resulting trend is strongly affected by local population level (which may or may not agree with trend for birds migrating through the site). Note that "local area" birds are those regularly observed at a station, though they may not breed or winter right at the site.

**I** Irruptive and irregular migrants. For species without a regular pattern of migratory movement, analysis window is usually the whole coverage period, as irruptive timing may vary among years. Annual indices represent annual variation in extent of irruption (although migration coverage may not cover entire period of movement). Over the long term population trends may be discernable despite the high degree of annual variation, but should be considered case by case.

**L** Birds from local area (not necessarily breeding or wintering at count site per se, but regularly observed there), showing no migratory peak in seasonal pattern. Trends are assumed to reflect population change in local area, which may or may not agree with trends at larger scales.

**S** Staging species (usually waterfowl and shorebirds) with pattern of migratory surge of which 75% or more is covered by the station. Some S species would be M if it were known that movement is unidirectional and there is minimal stopover. In most cases, however, trends may represent site use rather than population change, as there may be annual variation in use of the specialized stopover sites in the region, only one of which is being monitored. Trends should be interpreted case by case.

**MX** Regular migrant, but coverage at site a little too short to cover 75% of migration period. Shifts in timing of migration are not detectable from the data (e.g. change in timing due to climate change could produce a trend that is independent of true population size.) This is a subclass of "O" species, but designated separately to draw attention to species that could become "M" with modest extension of coverage.

**O** Other. Does not fit into any of the above groups. May have no clear migratory peak. May represent individuals of one or a combination of several categories: casual visitors, premigratory dispersal, tail ends of wintering populations, or other classes of birds whose numbers probably do not represent population change either at broad scale or in local breeding population.

## Bad Dates

In some cases, certain years or dates are removed from the analysis at a particular site and/or for a particular species at a site. The bad dates file can be accessed through the naturecounts R package.

## Analysis Methods

Long-term trends in migration counts were estimated independently for each species, site and season using a Bayesian hierarchical GAM framework with Integrated Nested Laplace Approximation (R-INLA, Rue et al. 2017) in R (version 3.1.3; R Core Team 2014). We estimated trends using log-linear regression, which included a smooth effect for year (i) and day of year (j) to model temporal patterns in population trajectories and the seasonal distributions of counts, respectively. We fit a cubic regression spline using the package mgcv (Wood 2011) with approximately 1 knot for every 4 years of data (following Smith and Edwards 2020), and 1 knot for every 8 days of data. The number of knots controls for the upper limit on the complexity of the smoother. We also include random annual fluctuations around the smoothed year effects (YE) to model population trajectories (similar to Smith and Edwards 2020), with an independent and identically distributed (IID) hierarchical year term (i.e., GAMYE).

For CMMN stations with more than one monitoring site (e.g., Long Point Bird Observatory), the regression also included a random site effect with an IID hierarchical site term. Models were all fit using a negative binomial distribution to generate indices of abundance and subsequently population trends.

Indices of Abundance The population trajectory for each species, site and season were defined be the collection of estimated annual indices of abundance (ni). These indices are calculated as the exponential mean daily count from the posterior distribution of the GAMYE model. We also calculated smoothed population trajectories for the GAMYE, as above, but without the parameter for annual fluctuations (YE). These smoothed indices (smooth_ni) provide an estimate of the medium and longer-term patterns of population change after removing the effect of the random annual fluctuations and form the basis of the trend calculations (Smith and Edwards 2020).

Trends Multiple metrics can be used to estimate a 'trend' from the estimated population trajectories. We provide endpoint trends calculated post-hoc from the smoothed population trajectories following methods outlined in the bbsBayes package (Edward and Smith 2021). Specifically, endpoint trend estimates are the geometric mean annual change (% per year) in the population trajectory, using an interval-specific ratio of the smoothed annual indices at the start and end of the time period (Sauer and Link 2011). 

Trend estimates and 95% credible intervals were back-transformed to annual rates of population change using 100\*exp(estimate)-1. Trend were calculated using the full dataset, as well as for the most recent 10-years, and three generations (Bird et al. 2020), the latter of which are informative to status assessments in Canada (e.g., see COSEWIC's Quantitative criteria and guideline for the status assessment of wildlife species). If the three-generation length was less than 10 years, the output reflects the 10-year trend.

Literature Cited

Bird, J. P., Martin, R., Akçakaya, H. R., Gilroy, J., Burfield, I. J., Garnett, S. T., Symes, A., Taylor, J., ekerciolu, Ç. H., & Butchart, S. H. M. (2020). Generation lengths of the world's birds and their implications for extinction risk. Conservation Biology, 34(5), 1252-1261. ttps://doi.org/10.1111/cobi.13486

Edwards, B., Smith, A. (2021). "bbsBayes: An R Package for Hierarchical Bayesian Analysis of North American Breeding Bird Survey Data." Journal of Open Research Software, 9. <doi:10.5334/jors.329>.

R Core Team. (2014). R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. [online] URL: <http://www.r-project.org>.

Rue, H., S. Martino, F. Lindgren, D. Simpson, and A. Riebler. (2014). INLA: Functions which allow to perform full Bayesian analysis of latent Gaussian models using Integrated Nested Laplace Approximation. [online] URL: <http://www.r-inla.org>.

Smith, A., Edwards, B. (2020). North American Breeding Bird Survey status and trend estimates to inform a wide-range of conservation needs, using a flexible Bayesian hierarchical generalized additive model. bioRxiv. doi: <https://doi.org/10.1101/2020.03.26.010215>

Wood, S.N. (2011) Fast stable restricted maximum likelihood and marginal likelihood estimation of semiparametric generalized linear models. Vol. 73, Journal of the Royal Statistical Society (B). p. 3--36.  
