---
output: html_document
editor_options: 
  chunk_output_type: console
---
# PLOT ANNUAL INDICES AND TRENDS

# Loop through sites and seasons and produce separate PDF plot
# function to call in various analysis functions

```{r setEnvironment07}

  require(tidyverse)
  require(ggplot2)


# directory to post plots

  max.yr <- 2021
  min.yr<-2011

  in.dir <- paste("Output/", max.yr, "/", sep = "")
  out.dir <- paste("Plots/", max.yr, "/", sep = "")

  anal.param <- read.csv("Data/CMMN_Analysis_ParameterValues.csv")
```

# read in list of sites/seasons to analyze

```{r speciesLoop}

#  for(p in 7:nrow(anal.param)){  # loop through sites and seasons
    
  p <-1 # for testing or running a single loop
  
site <- as.character(anal.param[p, "site"])


min.yr.filt <- anal.param[p,"min.year"]
max.yr.filt <- anal.param[p,"max.year"]

	# read in trend output

trnd <- read.csv(paste(in.dir, site, ".Trends.", max.yr, ".csv", sep = ""))
trnd <- trnd[order(trnd$sort_order),]
trnd <- trnd %>%
  filter(!(is.na(SpeciesCode)) & period == "all years") %>%
  select(-mean, -sd, -lcl, -mid, -ucl, -mode, -kld, -results_code, -trnd_order, -model_type, -period, -years)

trnd.spr <- trnd %>%
  filter(season == "Spring") %>%
  mutate(trnd.spr = trnd,
         post_prob.spr = post_prob,
         lower_ci_trend.spr = lower_ci,
         upper_ci_trend.spr = upper_ci,
         anal_code.spr = analysis_code)%>%
  select(-season, -lower_ci, -upper_ci, -analysis_code, -trnd, -post_prob)
        

trnd.fall <- trnd %>%
  filter(season == "Fall") %>%
  mutate(trnd.fall = trnd,
         post_prob.fall = post_prob,
         lower_ci_trend.fall = lower_ci,
         upper_ci_trend.fall = upper_ci,
         anal_code.fall = analysis_code)%>%
  select(-season, -lower_ci, -upper_ci, -analysis_code, -trnd, -post_prob)

options(digits = 2)

sp.trnd <- full_join(trnd.spr, trnd.fall, by = c("SpeciesCode", "area_code", "site", "species_id", "sort_order", "english_name", "french_name")) 
  
sp.trnd <- sp.trnd %>%
  mutate(sp.trnd = if_else((!is.na(trnd.spr) & !is.na(trnd.fall)), 
			paste(english_name, "/", " \n", french_name, "\n Spring (", anal_code.spr, ") : ", round(trnd.spr, digits = 2),  
			" (", round(lower_ci_trend.spr, digits = 2), ", ",
			round(upper_ci_trend.spr, digits = 2), "; ", round(post_prob.spr, digits = 2), ")\n Fall (", anal_code.fall, ") : ", 
			round( trnd.fall, digits = 2),  " (",
			round( lower_ci_trend.fall, digits = 2), ", ",
			round( upper_ci_trend.fall, digits = 2), "; ", round( post_prob.fall, digits = 2), ")", sep = ""), 
			if_else(
			is.na( trnd.spr), 
			paste( english_name, "/", "\n",  french_name, "\n Fall (", anal_code.fall, ") : ", 
			round( trnd.fall, digits = 2),  " (", round( lower_ci_trend.fall, digits = 2), ", ",
			round( upper_ci_trend.fall, digits = 2), "; ", 
			round( post_prob.fall, digits = 2), ")", sep = ""), 
			if_else(
			is.na( trnd.fall),
			paste( english_name, "/", "\n",  french_name, "\n Spring (", anal_code.spr, ") : ", 
			round( trnd.spr, digits = 2),  " (", round( lower_ci_trend.spr, digits = 2), ", ", 
			round( upper_ci_trend.spr, digits = 2), "; ", 
			round( post_prob.spr, digits = 2), ")", sep = ""), "NA"))))

	# read in annual index output

	index <- read.csv(paste(in.dir, site, ".AnnualIndices.", max.yr, ".csv", sep = ""))
 
#remove extreme outliers for plotting
	
	index$lower_ci <- ifelse(index$SD >= 4, 0, index$lower_ci)
	index$upper_ci <- ifelse(index$SD >= 4, 0, index$upper_ci)
	
	index <- index %>%
	  filter(!is.na(SpeciesCode) & period == "all years") %>%
	  dplyr::select(index, lower_ci, upper_ci,
	         SpeciesCode, year, season, area_code, analysis_code, model_type, species_id, #sort_order, 
english_name, french_name)
	
#To plot bt index 	
#	index$lower_ci.bt <- ifelse(index$SD >= 4, 0, index$lower_ci.bt)
#	index$upper_ci.bt <- ifelse(index$SD >= 4, 0, index$upper_ci.bt)
	
#	index <- index %>%
#	  filter(!is.na(SpeciesCode) & period == "all years") %>%
#	  dplyr::select(index.bt, lower_ci.bt, upper_ci.bt,
#	         SpeciesCode, year, season, area_code, analysis_code, model_type, species_id, #sort_order, 
#english_name, french_name)
	
# merge the two

#	sp.trnd[,'species_id']<-factor(sp.trnd[,'species_id'])
	
  plot.dat <- full_join(index, sp.trnd, by = c("area_code", "SpeciesCode", "species_id", "english_name", "french_name"))
	plot.dat <- plot.dat[order(plot.dat$sort_order),]
	
	plot.dat$SpeciesCode<-as.factor(plot.dat$SpeciesCode)

#Drop ay lines if speices_id missaligned. This is now fixed in the underlying code and will not happen again. 
	
plot.dat<-plot.dat %>% subset(!is.na(index))
	
# manually remove problem speices from a site based on 2018 analysis
#	if(site == "TCBO") {
#plot.dat <- plot.dat %>%
#  filter(!(SpeciesCode == "NOGO"), 
#         !(SpeciesCode == "RECR"), 
#         !(SpeciesCode == "RTLO"),  
#         !(SpeciesCode == "MERL"),
#         !(SpeciesCode == "CAJA"), 
#         !(SpeciesCode == "HASP")
# ) %>% droplevels()
	
  min.yr.filt <- ifelse(is.na(min.yr.filt), min(as.numeric(plot.dat$year)), min.yr.filt)
  max.yr.filt <- ifelse(is.na(max.yr.filt), max(as.numeric(plot.dat$year)), max.yr.filt)

# since max year in database might be greater than the max year we want to analyze, second filter

  max.yr.filt <- ifelse(max.yr.filt > max.yr,  max.yr, max.yr.filt)

 
# following is so that order of plots is correct
  plot.dat$sp.trnd <- factor(plot.dat$sp.trnd, levels=unique(plot.dat$sp.trnd))
  plot.dat <- subset(plot.dat, !is.na(year))
  plot.dat<-subset (plot.dat, !is.na(sp.trnd))
  
  sp.list <- as.character(unique(plot.dat$SpeciesCode))

  out.plot <- NULL
  i <- 1
  j <- 6

  for(t in 1:(ceiling(length(sp.list)/6))) {

  out.plot[[t]] <- ggplot(data = subset(plot.dat, SpeciesCode %in% sp.list[i:j]), aes(x = as.numeric(year), y = index, colour = season, shape = season)) +
	facet_wrap(~ sp.trnd, ncol = 2, scales = "free", as.table = TRUE) +
	geom_pointrange(aes(ymin = lower_ci, ymax = upper_ci, group = season, shape = season, width =1), size = 0.4) +
geom_smooth(aes(ymin = lower_ci, ymax = upper_ci, group = season, colour = season, fill = season, linetype = season), method = "loess",	size = 0.5, alpha = 0.1) + 
	xlab("Year") +
	ylab("Annual Index") +
  scale_x_continuous(breaks = seq(from = min.yr.filt, to = max.yr.filt, by = 4)) +
	scale_shape_manual(values = c(1,2)) +
	theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
	theme(legend.position = "none")
  
#To plot bt indiex values
 #out.plot[[t]] <- ggplot(data = subset(plot.dat, SpeciesCode %in% sp.list[i:j]), aes(x = as.numeric(year), y = index.bt, colour = season, shape = season)) +
	#facet_wrap(~ sp.trnd, ncol = 2, scales = "free", as.table = TRUE) +
	#geom_pointrange(aes(ymin = lower_ci.bt, ymax = upper_ci.bt, group = season, shape = season, width =1), size = 0.4) +
	#geom_smooth(aes(ymin = lower_ci.bt, ymax = upper_ci.bt, group = season, colour = season, fill = season, linetype = season), method = "loess",
	#size = 0.5, alpha = 0.1) + #linetype = "blank", 
	#theme_bw() +
	#xlab("Year") +
	#ylab("Annual Index") +
  #scale_y_continuous(trans="log10") +
  #scale_x_continuous(breaks = seq(from = min.yr.filt, to = max.yr.filt, by = 4)) +
	#scale_shape_manual(values = c(1,2)) +
	#theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
	#theme(legend.position = "none")

  i <- i + 6
  j <- j + 6
  }

  length(out.plot)
# Plot to PDF file
  pdf(paste(out.dir, site, ".IndexPlot.pdf", sep=""),
	height = 10, width = 8, paper = "letter")
  try(print(out.plot[[1]], silent=T))
  try(print(out.plot[[2]], silent=T))
  try(print(out.plot[[3]], silent=T))
  try(print(out.plot[[4]], silent=T))
  try(print(out.plot[[5]], silent=T))
  try(print(out.plot[[6]], silent=T))
  try(print(out.plot[[7]], silent=T))
  try(print(out.plot[[8]], silent=T))
  try(print(out.plot[[9]], silent=T))
  try(print(out.plot[[10]], silent=T))
  try(print(out.plot[[11]], silent=T))
  try(print(out.plot[[12]], silent=T))
  try(print(out.plot[[13]], silent=T))
  try(print(out.plot[[14]], silent=T))
  try(print(out.plot[[15]], silent=T))
  try(print(out.plot[[16]], silent=T))
  try(print(out.plot[[17]], silent=T))
  try(print(out.plot[[18]], silent=T))
  try(print(out.plot[[19]], silent=T))
  try(print(out.plot[[20]], silent=T))
  try(print(out.plot[[21]], silent=T))
  try(print(out.plot[[22]], silent=T))
  try(print(out.plot[[23]], silent=T))
  try(print(out.plot[[24]], silent=T))
  try(print(out.plot[[25]], silent=T))
  try(print(out.plot[[26]], silent=T))
  try(print(out.plot[[27]], silent=T))
  try(print(out.plot[[28]], silent=T))
  try(print(out.plot[[29]], silent=T))


while(!is.null(dev.list())) dev.off()
 
  }

```